[build]
  publish = "frontend"
  functions = "netlify/functions"
  command = "# no build command needed for static site"

[dev]
  publish = "frontend"
  functions = "netlify/functions"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
